name: Deploy Documentation

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install dependencies for the docs target
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate(); Pkg.activate("."); Pkg.resolve(); Pkg.build("docs")'

    - name: Build and deploy documentation
      env:
        DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
      run: |
        julia --project=. docs/make.jl
