name: Deploy Documentation

on:
  push:
    branches:
      - main

permissions:
  contents: write
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_STEP_DEBUG: true  

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Julia
      uses: julia-actions/setup-julia@v1
      with:
        version: '1.9'

    - name: Install dependencies
      run: |
        julia --project=. -e 'using Pkg; Pkg.instantiate()'

    - name: Build documentation
      run: |
        julia --project=. -e 'include("docs/make.jl")'

    - name: Debug build output
      run: |
        echo "Contents of docs/build:"
        ls -al docs/build

    - name: Upload combined output as GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: docs/build  
        name: github-pages  

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build

    env:
      ACTIONS_STEP_DEBUG: true  

    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
      with:
        artifact_name: github-pages
